name = "glimpse"
version = "0.0.2"

description = "Package loader and (theoretically) typechecker for glance"
licences = ["Apache-2.0"]
repository = { type = "github", user = "dusty-phillips", repo = "glimpse" }
links = [
  { title = "Website", href = "https://github.com/dusty-phillips/glimpse" },
]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
glance = ">= 0.11.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
pprint = ">= 1.0.3 and < 2.0.0"
